### PR TITLE
Querier transparent calls

### LINKED ISSUE #28: Generate queriers for interfaces
It would be helpful to provide utilities to easily query the contract.

For interfaces:

```rust
#[interface]
pub trait Cw1 {
  type Error: From<StdError>;
  
  #[msg(query)]
  fn find_member(&self, ctx: QueryCtx, member: String) -> Result<FindMemberResponse, Self::Error>;
}

// Generated:
pub struct Cw1Querier<'a> {
  contract: &'a Addr,
  querier: &'a cosmwasm_std::Querier,
}

impl<'a> Cw1Querier<'a> {
  pub fn new(querier: &'a cosmwasm_std::Querier, contract: Addr) -> Self { /* ... */ }
  
  pub fn find_member(&self, member: String) -> Result<FindMemberResponse, Self::Error>;
}
```

Additionally for contracts:

```rust
#[contract]
#[messages(cw1 as Cw1)]
pub struct Cw1WhitelistContract { /* ... */ }

#[derive(Serialize, Deserialize)]
pub struct Cw1WhitelistContractProxy(Addr);

impl Cw1WhitelistContractProxy {
  pub fn addr(&self) -> &Addr;
  
  pub fn cw1<'a>(&'a self, querier: &'a cosmwasm_std::Querier) -> Cw1Querier<'a> { /* .. */ }
}
```

This would allow keeping the contract in storage with semantical contract type, and then directly call queries. The access to underlying address is obviously required (eg. for sending submessages). Also implementing `impl From<Cw1WhitelistContractProxy> for Addr` should probably happen for free unwrapping.

### PR DESCRIPTION
**Pull request by jawoznia**
PR4
close  #28

### CODE REVIEW

**Comment by jawoznia** [comment]
close #113 
close #112 
close #111

File: sylvia-derive/src/input.rs [hunk 1]
```diff
@@ -243,4 +220,28 @@ impl<'a> ImplInput<'a> {
...
+        &self,
+        interfaces: &Interfaces,
+        variants: MsgVariants<'a>,
+    ) -> TokenStream {
+        let trait_module = interfaces
+            .interfaces()
+            .first()
+            .map(|interface| {
+                let module = &interface.module;
+                quote! { #module ::}
```
Comment (hashedone) [inline sylvia-derive/src/input.rs:234]: I really don't like adding this `::` to the module - it is a minor thing, but on usage, i prefer `#module :: Item` far more than `#module Item`, as it is more obvious that module is some module path (not usage of it looks like it could be some `let` or another keyword). I know you are saving some common keystrokes, but I find it impacting readability too much.

File: sylvia-derive/src/message.rs [hunk 2]
```diff
@@ -707,6 +707,29 @@ impl<'a> MsgVariants<'a> {
...
+
+        let methods_impl = variants
+            .iter()
+            .filter(|variant| variant.msg_type == MsgType::Query)
+            .map(|variant| variant.emit_querier_impl(trait_module));
+
+        #[cfg(not(tarpaulin_include))]
+        {
+            quote! {
+                impl <'a, C: #sylvia ::cw_std::CustomQuery> #trait_module Querier for #contract_module BoundQuerier<'a, C> {
```
Comment (hashedone) [inline sylvia-derive/src/message.rs:727]: Like here, see difference between `#sylvia ::cw_std::CustomQuery` (which obviously is the module where `cw_std`) and `#trait_module Querier` where it looks like it is some strange querier-prefix - not very obvious what to expect there to me.

File: sylvia-derive/src/parser.rs [hunk 3]
```diff
@@ -20,7 +20,7 @@ pub struct InterfaceArgs {
 /// Parser arguments for `contract` macro
 pub struct ContractArgs {
     /// Module name wrapping generated messages, by default no additional module is created
-    pub module: Option<Ident>,
+    pub module: Option<Path>,
```
Comment (hashedone) [inline sylvia-derive/src/parser.rs:23]: :+1:

File: sylvia/tests/dispatching.rs [hunk 4]
```diff
@@ -1,38 +1,49 @@
...
-    fn no_args_query(&self, ctx: QueryCtx) -> Result<EmptyQueryResponse, Self::Error>;
-
-    #[msg(query)]
-    fn argumented_query(&self, ctx: QueryCtx, user: Addr) -> Result<QueryResponse, Self::Error>;
+mod interface {
+    use cosmwasm_std::{Addr, Decimal, Response, StdError};
+    use sylvia::{
+        interface,
+        types::{ExecCtx, QueryCtx},
+    };
```
Comment (hashedone) [inline sylvia/tests/dispatching.rs:16]: Split it per module for consistency:

```rust
use sylvia::interface;
use sylvia::types::{ExecCtx, QueryCtx};
```

**Review by hashedone — APPROVED** [review]
Approved with comments, please apply small ones, the more refactor-related: please acknowledge and leave some track of them. In general I like how it is done and the API we god.

File: sylvia-derive/src/input.rs (hunk 1 above)
Comment (jawoznia) [reply sylvia-derive/src/input.rs:234]: I also don't like it but here I had to do it because we need this module to be used also for QueryMsg later on.
We could extract the module into TokenStream and then merge with QueryMsg and Querier

File: contracts/cw20-base/src/multitest/receiver.rs [hunk 5]
```diff
@@ -18,7 +18,7 @@ pub trait Receiver {
     ) -> Result<Response, Self::Error>;
 }
 
-#[contract]
+#[contract(module=crate::multitest::receiver_contract)]
```
[the remark this answers is not in the document]
Comment (jawoznia) [reply contracts/cw20-base/src/multitest/receiver.rs:21]: me too

File: sylvia-derive/src/input.rs (hunk 1 above)
Comment (jawoznia) [reply sylvia-derive/src/input.rs]: changed so that Option<&Path> is being passed to these methods and inside we merge the modules with proper types.

File: sylvia-derive/src/input.rs [hunk 6]
```diff
@@ -159,48 +140,44 @@ impl<'a> ImplInput<'a> {
...
         if is_trait {
-            return multitest_helpers;
+            let querier_bound_for_impl = self.emit_querier_for_bound_impl(&interfaces, variants);
+
+            #[cfg(not(tarpaulin_include))]
+            return quote! {
+                #multitest_helpers
+
+                #querier_bound_for_impl
+            };
```
[the remark this answers is not in the document]
Comment (jawoznia) [reply sylvia-derive/src/input.rs]: Done under this PR
